Sketched out the create command.

diff --git a/msm b/msm
--- a/msm
+++ b/msm
@@ -14,9 +14,47 @@
 
 source "msm.config"
 
+WHITELIST="white-list.txt"
+BANNED_IPS="banned-ips.txt"
+BANNED_PLAYERS="banned-players.txt"
+
 # See http://www.debian.org/doc/debian-policy/ch-opersys.html#s-sysvinit for
 # more information on debain init.d scripts, which may help you understand
 # this script.
+
+### Utility Functions
+
+# Esecutes the command "$1" as SERVER_USER
+as_user() {
+	if [ $(whoami) == $SERVER_USER ] ; then
+		bash -c "$1"
+	else
+		su - $SERVER_USER -s /bin/bash -c "$1"
+	fi
+}
+
+manager_create_server() {
+    local regex="[a-zA-Z0-9\-_]+"
+    
+    if [[ $1 =~ $regex ]]; then
+        if [[ -e ${SERVER_STORAGE_PATH}/$1 ]]; then
+            echo "A server with that name already exists."
+            exit 1
+        else
+            printf "Creating server directory... "
+            as_user "mkdir -p ${SERVER_STORAGE_PATH}/$1"
+            as_user "touch $SERVER_STORAGE_PATH/$1/$WHITELIST"
+            as_user "touch $SERVER_STORAGE_PATH/$1/$BANNED_IPS"
+            as_user "touch $SERVER_STORAGE_PATH/$1/$BANNED_PLAYERS"
+            echo "Done."
+        fi
+    else
+        echo -e "Invalid name: may only contain letters, numbers, a dash or an underscore."
+    fi
+}
+
+
+### Script Options
 
 case "$1" in
     start)
@@ -30,6 +68,8 @@ case "$1" in
         ;;
     create)
         # Create a new server
+        manager_create_server $2
+        
         ;;
     delete)
         # Delete an existing server, with confirmation
